
# congribution 먹는 뱀 생성기
name: Generate Snake

# 액션 실행 스케줄 (12시간마다)
on:
  schedule:
    - cron: "0 */12 * * *"

# 이 명령을 사용하면 Actions 탭에서 Action을 수동으로 실행할 수 있다.
  workflow_dispatch:

# workflow 동작 순서
jobs:
  # build라는 job을 한다.
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # job이 실행할 작업의 시퀀스
    steps:

    # $GITHUB_WORKSPACE 하의 나의 repos에 checkout하여, workflow에서 접근하게 해줌.
      - uses: actions/checkout@v2
      - run: echo $GITHUB_WORKSPACE

    # 뱀 생성
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          # "output" 브랜치에 파일을 생성하도록 되어있음.
          outputs: |
            dist/github-snake-dark.svg?palette=github-dark

     # 빌드 상태 출력
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
